# Generated by Django 6.0.5 on 2026-05-31 18:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.CharField(editable=False, max_length=20, unique=True)),
                ('montant_demande', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1000)])),
                ('montant_accorde', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('frg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Fonds de Risques et de Garantie')),
                ('montant_net_debloque', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant net débloqué')),
                ('frequence_remboursement', models.CharField(choices=[('HEBDOMADAIRE', 'Hebdomadaire'), ('MENSUEL', 'Mensuel')], default='MENSUEL', max_length=20)),
                ('nombre_echeances', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('mode_deblocage', models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('VIREMENT', 'Virement bancaire')], default='ESPECES', max_length=20)),
                ('date_soumission', models.DateField(blank=True, null=True)),
                ('date_approbation', models.DateField(blank=True, null=True)),
                ('date_deblocage', models.DateField(blank=True, null=True)),
                ('date_echeance_finale', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('EN_ETUDE', 'En étude'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté'), ('DEBLOQUE', 'Débloqué'), ('EN_COURS', 'En cours de remboursement'), ('SOLDE', 'Soldé'), ('EN_DEFAUT', 'En défaut')], default='BROUILLON', max_length=20)),
                ('motif_rejet', models.TextField(blank=True)),
                ('montant_rembourse', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_restant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('penalites_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers_credit', to='membres.membre')),
            ],
            options={
                'verbose_name': 'Dossier de Crédit',
                'verbose_name_plural': 'Dossiers de Crédit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneEcheancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_echeance', models.PositiveIntegerField()),
                ('date_echeance', models.DateField()),
                ('montant_echeance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('penalite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('PARTIELLEMENT_PAYE', 'Partiellement payé'), ('EN_RETARD', 'En retard')], default='EN_ATTENTE', max_length=25)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeancier', to='credits.dossiercredit')),
            ],
            options={
                'verbose_name': "Ligne d'Échéancier",
                'verbose_name_plural': "Lignes d'Échéancier",
                'ordering': ['numero_echeance'],
                'unique_together': {('dossier', 'numero_echeance')},
            },
        ),
    ]
