# Generated by Django 6.0.5 on 2026-06-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiercredit',
            name='frg_date_versement',
            field=models.DateField(blank=True, null=True, verbose_name='Date versement FRG'),
        ),
        migrations.AddField(
            model_name='dossiercredit',
            name='frg_mode_versement',
            field=models.CharField(blank=True, choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money')], max_length=20),
        ),
        migrations.AddField(
            model_name='dossiercredit',
            name='frg_verse',
            field=models.BooleanField(default=False, verbose_name='FRG versé'),
        ),
    ]
