# Generated by Django 6.0.5 on 2026-06-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(default='MicroFinance+', max_length=100)),
                ('slogan', models.CharField(blank=True, default='CTL Group', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('couleur_primaire', models.CharField(default='#1A6FD4', max_length=7)),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configuration',
            },
        ),
    ]
