# Generated by Django 6.0.5 on 2026-05-31 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_membre', models.CharField(editable=False, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('type_piece', models.CharField(choices=[('CNI', "Carte Nationale d'Identité"), ('PASSEPORT', 'Passeport'), ('PERMIS', 'Permis de conduire')], max_length=20)),
                ('numero_piece', models.CharField(max_length=50, unique=True)),
                ('date_expiration_piece', models.DateField()),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s\\-]{8,20}$', 'Numéro invalide')])),
                ('adresse', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profession', models.CharField(max_length=100)),
                ('secteur_activite', models.CharField(max_length=100)),
                ('revenu_mensuel_estime', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_adhesion', models.DateField(auto_now_add=True)),
                ('frais_adhesion', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('frais_adhesion_paye', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('EXCLU', 'Exclu')], default='EN_ATTENTE', max_length=20)),
                ('beneficiaire_nom', models.CharField(blank=True, max_length=200)),
                ('beneficiaire_telephone', models.CharField(blank=True, max_length=20)),
                ('beneficiaire_lien', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['-date_adhesion'],
            },
        ),
    ]
