# Generated by Django 6.0.5 on 2026-05-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='copie_piece_identite',
            field=models.FileField(default='', upload_to='membres/pieces_identite/', verbose_name="Copie pièce d'identité (légalisée)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membre',
            name='justificatif_domicile',
            field=models.FileField(default='', upload_to='membres/justificatifs_domicile/', verbose_name='Justificatif de domicile'),
            preserve_default=False,
        ),
    ]
