# Generated by Django 6.0.5 on 2026-06-02 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0002_membre_copie_piece_identite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='approuve_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres_approuves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membre',
            name='date_approbation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='date_paiement_frais',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='mode_paiement_frais',
            field=models.CharField(blank=True, choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money')], max_length=20),
        ),
        migrations.AddField(
            model_name='membre',
            name='motif_rejet',
            field=models.TextField(blank=True),
        ),
    ]
