# Generated by Django 6.0.5 on 2026-06-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0003_membre_approuve_par_membre_date_approbation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté'), ('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('EXCLU', 'Exclu')], default='EN_ATTENTE', max_length=20),
        ),
    ]
