# Generated by Django 6.0.5 on 2026-05-31 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierRecouvrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.CharField(editable=False, max_length=20, unique=True)),
                ('etape_actuelle', models.CharField(choices=[('RELANCE_1', 'Relance amiable (J+7)'), ('RELANCE_2', 'Mise en demeure (J+30)'), ('RELANCE_3', 'Intervention superviseur (J+60)'), ('RELANCE_4', 'Procédure légale (J+90)')], default='RELANCE_1', max_length=20)),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', 'En cours'), ('RESOLU', 'Résolu'), ('PERTE', 'Passé en perte')], default='OUVERT', max_length=20)),
                ('montant_en_defaut', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_recouvre', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_ouverture', models.DateField(auto_now_add=True)),
                ('date_resolution', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('assigne_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers_recouvrement', to=settings.AUTH_USER_MODEL)),
                ('credit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dossier_recouvrement', to='credits.dossiercredit')),
            ],
            options={
                'verbose_name': 'Dossier de Recouvrement',
                'verbose_name_plural': 'Dossiers de Recouvrement',
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='ActionRecouvrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('APPEL', 'Appel téléphonique'), ('SMS', 'SMS'), ('VISITE', 'Visite domicile'), ('COURRIER', 'Courrier'), ('MISE_EN_DEMEURE', 'Mise en demeure'), ('AUTRE', 'Autre')], max_length=20)),
                ('date_action', models.DateField()),
                ('resultat', models.CharField(choices=[('SANS_REPONSE', 'Sans réponse'), ('PROMESSE_PAIEMENT', 'Promesse de paiement'), ('PAIEMENT_PARTIEL', 'Paiement partiel'), ('PAIEMENT_TOTAL', 'Paiement total'), ('REFUSE', 'Refus de paiement')], max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('effectuee_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions_recouvrement', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='recouvrement.dossierrecouvrement')),
            ],
            options={
                'verbose_name': 'Action de Recouvrement',
                'verbose_name_plural': 'Actions de Recouvrement',
                'ordering': ['-date_action'],
            },
        ),
    ]
