# Generated by Django 6.0.5 on 2026-05-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresMicrofinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_structure', models.CharField(default='Ma Microfinance', max_length=200)),
                ('sigle', models.CharField(blank=True, max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ninea', models.CharField(blank=True, max_length=50, verbose_name='NINEA')),
                ('rccm', models.CharField(blank=True, max_length=50, verbose_name='RCCM')),
                ('frais_adhesion', models.DecimalField(decimal_places=2, default=5000, max_digits=10, verbose_name="Frais d'adhésion (FCFA)")),
                ('taux_frg', models.DecimalField(decimal_places=4, default=0.1667, max_digits=5, verbose_name='Taux FRG (défaut : 1/6)')),
                ('penalite_retard', models.DecimalField(decimal_places=2, default=2000, max_digits=10, verbose_name='Pénalité de retard (FCFA/jour)')),
                ('plafond_credit_global', models.DecimalField(decimal_places=2, default=10000000, max_digits=14, verbose_name='Plafond crédit global (FCFA)')),
                ('ratio_concentration_max', models.DecimalField(decimal_places=2, default=25, max_digits=5, verbose_name='Ratio de concentration max (%)')),
                ('seuil_par30', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='Seuil PAR 30 acceptable (%)')),
                ('seuil_par90', models.DecimalField(decimal_places=2, default=3, max_digits=5, verbose_name='Seuil PAR 90 acceptable (%)')),
                ('date_debut_exercice', models.DateField(blank=True, null=True)),
                ('date_fin_exercice', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres Microfinance',
                'verbose_name_plural': 'Paramètres Microfinance',
            },
        ),
    ]
