# Generated by Django 6.0.5 on 2026-06-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresmicrofinance',
            name='date_solde_initial',
            field=models.DateField(blank=True, null=True, verbose_name='Date de la mise à jour du solde initial'),
        ),
        migrations.AddField(
            model_name='parametresmicrofinance',
            name='solde_initial_caisse',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Solde initial de la caisse (FCFA)'),
        ),
    ]
