# Generated by Django 6.0.5 on 2026-05-31 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credits', '0001_initial'),
        ('remboursements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcritureCompteGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ecriture', models.CharField(editable=False, max_length=20, unique=True)),
                ('type_ecriture', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10)),
                ('categorie', models.CharField(choices=[('ADHESION', "Frais d'adhésion"), ('FRG', 'Fonds de Risques et de Garantie'), ('DEBLOCAGE', 'Déblocage crédit'), ('REMBOURSEMENT', 'Remboursement'), ('PENALITE', 'Pénalité de retard'), ('AUTRE', 'Autre')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('solde_apres', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('date_ecriture', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dossier_credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ecritures', to='credits.dossiercredit')),
                ('remboursement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ecritures', to='remboursements.remboursement')),
                ('saisi_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Écriture Compte Global',
                'verbose_name_plural': 'Écritures Compte Global',
                'ordering': ['-created_at'],
            },
        ),
    ]
